---
title: 'Project #2'
output:
  word_document: default
  html_document: default
date: "2023-03-07"
---

```{r}
#load the mlbench package which has the BreastCancer data set
require(mlbench)

# if you don't have any required package, use the install.packages() command
# load the data set
data(BreastCancer)
ls(BreastCancer)
# Remove Missing Values
BreastCancer <- na.omit(BreastCancer) 
# remove unique identifier
BreastCancer$Id <- NULL 
head(BreastCancer)
str(BreastCancer)
df2 <- data.frame(sapply(BreastCancer[1:9], function(x)
as.numeric(as.character(x))))
z <- scale(df2[,1:9],center=TRUE,scale=TRUE)
head(z)

```
```{r}
#Support Machine Learning
library(e1071)
library(caret)
mysvm <- svm(Class ~ ., BreastCancer)
mysvm.pred <- predict(mysvm, BreastCancer)
table(mysvm.pred,BreastCancer$Class)
str(BreastCancer)

svmfit <- svm(Class ~., data = BreastCancer, kernal = "linear", cost = 1, scale = FALSE)
print(svmfit)
str(mysvm)

#Confusion Matrix SVM
CM <- confusionMatrix(as.factor(mysvm.pred), as.factor(BreastCancer$Class))
CM

```
```{r}
#Exploring Variables to use for our prediction
library(klaR)
mynb <- NaiveBayes(Class ~ ., BreastCancer)
str(mynb)
mynb$tables
mynb$apriori
mynb.pred <- predict(mynb,BreastCancer)
head(mynb.pred$class)
table(mynb.pred$class,BreastCancer$Class)
str(mysvm.pred)
str(mynb.pred)

```
```{r}
#Neural Network set up
library(nnet)
library(neuralnet)
for (i in c(1:9)){
BreastCancer[,i] <-(as.numeric(BreastCancer[,i])-min(as.numeric(BreastCancer[,i]))) /
  (max(as.numeric(BreastCancer[,i]))-min(as.numeric(BreastCancer[,i])))
}
mynnet <- neuralnet(Class ~ ., BreastCancer, hidden=c(5,4))
mynnet.pred <- predict(mynnet,BreastCancer,type="class")
str(mynnet.pred)
head(BreastCancer$Class)
```

```{r}
#Converting classification for Neural network table
head(mynnet.pred[,])
mynnetClass=ifelse(mynnet.pred[,1]>.5, "benign", "malignant")
head(mynnetClass)
head(BreastCancer)
bcClass=ifelse(BreastCancer$Class=="benign", 1, 0)
head(bcClass)

table(mynnetClass,BreastCancer$Class)

```
```{r}
#Decision trees
library(MASS)
library(rpart)
library(rpart.plot)
mytree <- rpart(Class ~ ., BreastCancer)
plot(mytree); text(mytree) 
summary(mytree)
mytree.pred <- predict(mytree,BreastCancer,type="class")
table(mytree.pred,BreastCancer$Class)
str(mytree)
rpart.rules(mytree)
rpart.plot(mytree)
```
```{r}
# Leave-1-Out Cross Validation (LOOCV)
ans <- numeric(length(BreastCancer[,1]))
for (i in 1:length(BreastCancer[,1])) {
  mytree <- rpart(Class ~ ., BreastCancer[-i,])
  mytree.pred <- predict(mytree,BreastCancer[i,],type="class")
  ans[i] <- mytree.pred
}
ans <- factor(ans,labels=levels(BreastCancer$Class))
table(ans,BreastCancer$Class)
```
```{r}
#Regularised Discriminant Analysis
library(klaR)
myrda <- rda(Class ~ ., BreastCancer)
myrda.pred <- predict(myrda, BreastCancer)

table(myrda.pred$class,BreastCancer$Class)
```
```{r}
#Random Forests
library(randomForest)
myrf <- randomForest(Class ~ ., BreastCancer)
myrf.pred <- predict(myrf, BreastCancer)
head(myrf.pred)
table(myrf.pred, BreastCancer$Class)
```
```{r}
#Combine classes
combine.classes<-data.frame(myrf.pred, myrda.pred$class,#myqda.pred, 
                            mytree.pred,mynnetClass,mysvm.pred, mynb.pred$class, BreastCancer$Class)
head(combine.classes)
head(myrf.pred)
head(myrda.pred)
combine.classes$myrf.pred<-ifelse(combine.classes$myrf.pred=="benign", 0, 1)
combine.classes[,2]<-ifelse(combine.classes[,2]=="benign", 0, 1)
combine.classes[,3]<-ifelse(combine.classes[,3]=="benign", 0, 1)
combine.classes[,4]<-ifelse(combine.classes[,4]=="benign", 0, 1)
combine.classes[,5]<-ifelse(combine.classes[,5]=="benign", 0, 1)
combine.classes[,6]<-ifelse(combine.classes[,6]=="benign", 0, 1)
str(combine.classes)
```
```{r}
#Majority Rule Ensemble Approach 
combine.cl<-combine.classes[, -c(7,8)]
majority.vote=rowSums(combine.classes[,-c(7,8)])
head(majority.vote)
head(combine.cl)
combine.classes[,7]<-rowSums(combine.classes[,-c(7,8)])
combine.classes[,8]<-ifelse(combine.classes[,7]>=4, "malignant", "benign")
table(combine.classes[,8], BreastCancer$Class)
decTree<-rpart(BreastCancer.Class~., combine.classes)
str(decTree)
decTree
summary(decTree)
rpart.rules(decTree)
rpart.plot(decTree)
```

